# Generated by Django 3.0.8 on 2020-07-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmi', models.CharField(blank=True, max_length=128, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=128, null=True)),
                ('reading', models.CharField(blank=True, max_length=128, null=True)),
                ('dateTime', models.CharField(blank=True, max_length=128, null=True)),
                ('flowName', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
